-- Unity Shader Development Setup for Neovim
-- This is mostly here for reference don't expect to work drag and drop in your config!!!!
--
-- This configures:
--   1. Filetype detection for Unity shader files (.shader, .cginc, .compute, .hlsl, etc.)
--   2. Treesitter grammars for HLSL and GLSL syntax highlighting
--   3. ShaderHighlight plugin for ShaderLab vim syntax (no treesitter grammar exists)
--   4. Buffer-local settings (indentation, comments) for shader editing
--   5. shader-language-server LSP for HLSL (diagnostics, completion, goto-def, hover)
--   6. DXC null-byte diagnostic handler (prevents E976 Blob-as-String crashes)
--
-- LSP setup:
--   - glsl_analyzer should be added to the `servers` table in init.lua (Mason-managed)
--   - shader-language-server is configured here as a custom LSP (cargo-installed, not in Mason)
--
-- Prerequisites:
--   - cargo install shader_language_server
--   - libdxcompiler.so at ~/.cargo/bin/ (built from source or prebuilt)
--   - .shader-language-server.json at Unity project root (generated by setup-shader-lsp.sh)
--
-- NOTE: .shader files DO NOT get LSP support -- the server rejects the 'shaderlab'
-- language ID. Only .compute, .cginc, .hlsl files get full LSP features.

-----------------------------------------------------------------------
-- Filetype Detection
-----------------------------------------------------------------------
vim.filetype.add({
	extension = {
		shader = "shaderlab",
		cginc = "hlsl",
		hlsli = "hlsl",
		compute = "hlsl",
		cg = "hlsl",
		glsl = "glsl",
		vert = "glsl",
		frag = "glsl",
		geom = "glsl",
		tesc = "glsl",
		tese = "glsl",
		comp = "glsl",
	},
})

-----------------------------------------------------------------------
-- Buffer-local settings for shader files
-----------------------------------------------------------------------
vim.api.nvim_create_autocmd("FileType", {
	pattern = { "shaderlab", "hlsl", "glsl" },
	group = vim.api.nvim_create_augroup("unity-shader-settings", { clear = true }),
	callback = function()
		vim.bo.tabstop = 4
		vim.bo.shiftwidth = 4
		vim.bo.softtabstop = 4
		vim.bo.expandtab = true
		vim.wo.wrap = false
		vim.bo.commentstring = "// %s"
	end,
	desc = "Buffer-local settings for Unity shader files",
})

-----------------------------------------------------------------------
-- DXC null-byte diagnostic handler
-----------------------------------------------------------------------
-- DXC emits null-terminated C strings in error messages. shader-language-server
-- passes them through raw, and Neovim treats a string containing \0 as a Blob.
-- This crashes diagnostic display plugins (diagflow, Telescope diagnostics, etc.)
-- with: "E976: Using a Blob as a String"
local original_handler = vim.lsp.handlers["textDocument/publishDiagnostics"]
vim.lsp.handlers["textDocument/publishDiagnostics"] = function(err, result, ctx, config)
	if result and result.diagnostics then
		for _, diagnostic in ipairs(result.diagnostics) do
			if diagnostic.message then
				diagnostic.message = diagnostic.message:gsub("%z", "")
			end
		end
	end
	return original_handler(err, result, ctx, config)
end

-----------------------------------------------------------------------
-- shader-language-server (HLSL LSP)
-----------------------------------------------------------------------
-- The server's workspace/configuration request overwrites CLI config
-- unless we also pass the config as LSP settings. Both are needed.
vim.api.nvim_create_autocmd("FileType", {
	pattern = { "hlsl" },
	group = vim.api.nvim_create_augroup("shader-language-server", { clear = true }),
	callback = function(args)
		if vim.fn.executable("shader-language-server") ~= 1 then
			return
		end

		local root_dir = vim.fs.root(args.buf, function(name, _)
			return name == "Assets"
		end)
		if not root_dir then
			root_dir = vim.fs.root(args.buf, { ".git", ".shader-language-server.json" })
		end

		local cmd = { "shader-language-server", "--hlsl", "--stdio" }
		local settings = {}

		if root_dir then
			local config_path = root_dir .. "/.shader-language-server.json"
			local f = io.open(config_path, "r")
			if f then
				local content = f:read("*a")
				f:close()
				cmd = { "shader-language-server", "--hlsl", "--config-file", config_path, "--stdio" }
				local ok, parsed = pcall(vim.json.decode, content)
				if ok then
					settings = { ["shader-validator"] = parsed }
				end
			end
		end

		vim.lsp.start({
			name = "shader-language-server",
			cmd = cmd,
			root_dir = root_dir,
			settings = settings,
		})
	end,
	desc = "Start shader-language-server for HLSL files",
})

-----------------------------------------------------------------------
-- Plugin specs
-----------------------------------------------------------------------
return {

	{
		"kalvinpearce/ShaderHighlight",
		ft = { "shaderlab", "hlsl", "glsl", "cg" },
	},

	{
		"nvim-treesitter/nvim-treesitter",
		opts = function(_, opts)
			opts.ensure_installed = opts.ensure_installed or {}
			vim.list_extend(opts.ensure_installed, { "hlsl", "glsl" })
		end,
	},
}
